### PR TITLE
Component unmount fix

### PR DESCRIPTION
**Pull request by DNFcode**
Hi! Thanks for your component. 
I found a little problem with it's unmounting though.
This kind of error occurs if I'm navigating using react-router.
```
setState(…): Can only update a mounted or mounting component.
This usually means you called setState() on an unmounted component. This is a no-op
```

### CODE REVIEW

**Comment by DNFcode** [comment]
The only problem is.. I wasn't able to figure out what the problem is with testing.
`Uncaught TypeError: window.scrollTo is not a function`

But it works for me just fine.

**Comment by dirtyredz** [comment]
Im unable to replicate the error your recieving, could you tell me which version of react and react-router your using.

**Comment by DNFcode** [comment]
"react": "15.4.1"
"react-router": "3.0.0"
And it's marked by React like warning not error (sorry for misleading).
The problem may be caused not by react router, but by any kind of action that will umnount the component. And if you'll try to scroll after the component unmount you'll see these warnings.

**Comment by dirtyredz** [comment]
Thanks for the clarification. ill take a look at it.

**Comment by dirtyredz** [comment]
thxs for the issue notification and providing a fix. After reviewing your fix and adding functionatlity into my testing I see that `window.removeEventListener` wasnt properly removing this.HandleScroll due to `bind(this)` creating a new refrence. More on this [https://gist.github.com/Restuta/e400a555ba24daa396cc](url)

**Comment by dirtyredz** [comment]
Ive also updated dependancies and fix a NodeJS and unit testing error.  version 1.5.8 has been pushed to NPM.

**Pull request merged**
